### ISSUE TITLE
Replicating the results 

### ISSUE THREAD

**Issue by ardakdemir** [dmis-lab/bioasq-biobert#7]
Dear authors, 

Thanks a lot for providing a very helpful repository. I am trying to replicate the results you mention on the README page for factoid-6b test batch 1 :

```
0.0 0.4358974358974359 0.6153846153846154 0.5072649572649572 0.0 0.0 0.0 0.0 0.0 0.0
```

It is not clear from the repository that which training dataset (train6b-factoid, train7b-factoid or combination of them ) is used to train the model which obtains the above mentioned scores.

By looking at the descriptions, it seems that train-6b factoid is used but I would be glad if you can clarify.

Kind regards 

Arda

**Comment by wonjininfo** [comment]
Hi Arda,
Yes, you need to use train-6b when you try to evaluate test-6b files.
Train-7b datasets is composed of train-6b and test-6b datasets (although there may be small differences; majorly corrections). 
So it is mandatory to use corresponding dataset.
Thanks!!
Wonjin

**Comment by ardakdemir** [comment]
Thanks a lot for your reply!
So the results mentioned are obtained using train-6b on the test-batch 1 of the factoid type questions, right?

**Comment by wonjininfo** [comment]
Oh the values on the README file is not a exact representation of our results. 
**_Please find our scores from the paper._** 
Also, since the dataset is quite small in terms of a single batch, it is important to average your scores across the batches. 

I am sure that the value `0.0 0.4358974358974359 0.6153846153846154 0.5072649572649572 0.0 0.0 0.0 0.0 0.0 0.0 ` is from our model but I forgot which experiment (=dataset) it comes from. It might be a result of other version of dataset or other batch (ex. Test-5b-batch 3).

**Comment by ardakdemir** [comment]
Thanks a lot for the clarification!
I will keep these in my mind!

Arda
